#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.1.84:3306/a_ljy_db
#    username: a_ljy_user
#    password: '!adnstyleDB'
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#  thymeleaf:
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#mybatis:
#  type-aliases-package: com.adnstyle.myboard.model.domain
#  mapper-locations: mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ljy329s
    username: root
    password: '1234'
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
mybatis:
  type-aliases-package: com.adnstyle.myboard.model.domain
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

